[package]
name = "rust_practice_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
chrono = "0.4.23"
thiserror = "1.0.38"
crossbeam-channel ="0.5.6"